### ISSUE TITLE
Bad Exit Status - Kernal 5.2.0-2parrot1-amd64

### ISSUE THREAD

**Issue by Shiftylab** [smlinux/rtl8723de#54]
Receiving an error when I run sudo dkms install rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414

> Kernel preparation unnecessary for this kernel.  Skipping...
> 
> Building module:
> cleaning build area...
> 'make' all KVER=5.2.0-2parrot1-amd64....(bad exit status: 2)
> Error! Bad return status for module build on kernel: 5.2.0-2parrot1-amd64 (x86_64)
> Consult /var/lib/dkms/rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414/build/make.log for more information.

Here is the log file from that error.

> DKMS make.log for rtl8723de-5.1.1.8_21285.20171026_COEX20170111-1414 for kernel 5.2.0-2parrot1-amd64 (x86_64)
> Mon 14 Oct 2019 04:48:00 AM EDT
> make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.2.0-2parrot1-amd64/build M=/var/lib/dkms/rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414/build  modules
> make[1]: Entering directory '/usr/src/linux-headers-5.2.0-2parrot1-amd64'
>   CC [M]  /var/lib/dkms/rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414/build/core/rtw_cmd.o
> In file included from /var/lib/dkms/rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414/build/include/osdep_service.h:41,
>                  from /var/lib/dkms/rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414/build/include/drv_types.h:32,
>                  from /var/lib/dkms/rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414/build/core/rtw_cmd.c:22:
> /var/lib/dkms/rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414/build/include/osdep_service_linux.h: In function ‘_init_timer’:
> /var/lib/dkms/rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414/build/include/osdep_service_linux.h:287:8: error: ‘_timer’ {aka ‘struct timer_list’} has no member named ‘data’
>   ptimer->data = (unsigned long)cntx;
>         ^~
> /var/lib/dkms/rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414/build/include/osdep_service_linux.h:288:2: error: implicit declaration of function ‘init_timer’; did you mean ‘_init_timer’? [-Werror=implicit-function-declaration]
>   init_timer(ptimer);
>   ^~~~~~~~~~
>   _init_timer
> In file included from /var/lib/dkms/rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414/build/include/drv_types.h:35,
>                  from /var/lib/dkms/rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414/build/core/rtw_cmd.c:22:
> /var/lib/dkms/rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414/build/include/wifi.h: At top level:
> /var/lib/dkms/rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414/build/include/wifi.h:1006: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
>  #define IEEE80211_MAX_AMPDU_BUF 0x40
>  
> In file included from /var/lib/dkms/rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414/build/include/osdep_service_linux.h:86,
>                  from /var/lib/dkms/rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414/build/include/osdep_service.h:41,
>                  from /var/lib/dkms/rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414/build/include/drv_types.h:32,
>                  from /var/lib/dkms/rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414/build/core/rtw_cmd.c:22:
> /usr/src/linux-headers-5.2.0-2parrot1-common/include/linux/ieee80211.h:1441: note: this is the location of the previous definition
>  #define IEEE80211_MAX_AMPDU_BUF  0x100
>  
> cc1: some warnings being treated as errors
> make[4]: *** [/usr/src/linux-headers-5.2.0-2parrot1-common/scripts/Makefile.build:284: /var/lib/dkms/rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414/build/core/rtw_cmd.o] Error 1
> make[3]: *** [/usr/src/linux-headers-5.2.0-2parrot1-common/Makefile:1610: _module_/var/lib/dkms/rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414/build] Error 2
> make[2]: *** [Makefile:179: sub-make] Error 2
> make[1]: *** [Makefile:8: all] Error 2
> make[1]: Leaving directory '/usr/src/linux-headers-5.2.0-2parrot1-amd64'
> make: *** [Makefile:1884: modules] Error 2
